# Generated by Django 5.2.5 on 2025-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_alter_order_status_deliverypartnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.DeleteModel(
            name='DeliveryPartnerProfile',
        ),
    ]
